### ISSUE TITLE
Use in non-MVC site?

### ISSUE THREAD

**Issue by winzig** [jgauffin/CorsProxy#1]
This project is very interesting, and based on all the people running into these issues, it's surprising I'm the first person to star it! I'm guessing most people running into this issue are not on IIS.

In any event, in your blog you show how to integrate it with an MVC project:

routes.EnableCorsProxy();

And there's mention of it working in other flavors of ASP.NET due to it being an IHttpHandler, yet I'm having a hard time seeing the proper way of integrating it for a regular ASP.NET site. Any pointers? Thanks!

**Comment by jgauffin** [comment]
You can activate it in web.config using a custom path: http://msdn.microsoft.com/en-us/library/vstudio/ms228090(v=vs.100).aspx

Another sample: http://support.microsoft.com/kb/308001
