### ISSUE TITLE
data not passed correctly

### ISSUE THREAD

**Issue by mmoron** [jgauffin/CorsProxy#2]
Hi,

first of all thank you for creating this. You've saved my life:-). 

while using this solution I found an issue preventing me from correctly using data in ajax get request. When I do something like this:

``` javascript
$.ajax({
    url: 'http://www.example.com/Foo/Bar?x=1&y=2',
    data: { id : 1 },
    crossDomain: true
});
```

url is correctly passed with `X-CorsProxy-Url` header, however whatever is in data is not. Content of data is attached to corsproxy url (so a call is done to an address like `(...)/corsproxy?id=1` with a correct `X-CorsProxy-Url` header containing content of `url` attribute) and is not redirected further.

I've managed to fix this by simply changing your .js file from:

``` javascript
var url = options.url;
```

to:

``` javascript
var url = options.url + '&' + options.data;
```

in my scenario this will work (I'm sure that `options.data` is never empty and there are always other elements in query string so appending new ones with '&' is valid), but in general this might need more work (like checking whether there is a query string at all and use '?' instead of '&' and so on).

Best Regards

**Comment by jgauffin** [comment]
That's just a problem för GET requests as bodies are prohibited according to the HTTP specification. Thats why jquery merges the data into the URI.

Try it with POST/PUT and you'll see that the body working as expected.

**Comment by mmoron** [comment]
Yes, it works for POST/PUT requests. Unfortunatelly I can't change requests so I needed a solution that will work for GET parameters. Change I've described seems to achieve what I need. I'm raising this more as a reference and pottential info for anyone having same issue in the future.

Regards

**Comment by jgauffin** [comment]
fixed
