### ISSUE TITLE
mvc default Route

### ISSUE THREAD

**Issue by werddomain** [jgauffin/CorsProxy#3]
when installing this package to mvc all default route ex RedirectToAction("Index", "Home") is generated as /corsproxy?action=Index&controller=Home

then i get a 501 error : X-CorsProxy-Url was not specified. The corsproxy should only be invoked from the proxy javascript.

**Comment by werddomain** [comment]
i have found a solution : 

i have created a route constraint:
 public class NotEnableCorsProxyContrains : IRouteConstraint {

```
    public bool Match(HttpContextBase httpContext, Route route, string parameterName, RouteValueDictionary values, RouteDirection routeDirection)
    {      
        var controller = values["controller"].ToString().ToLower();
        return controller != "corsproxy";
    }
}
```

then using in all my routes:

```
 routes.MapRoute(
            name: "Default",
            url: "{controller}/{action}/{id}",
            defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional },
            constraints: new { controller = new NotEnableCorsProxyContrains() }
        );
```

and i place the   routes.EnableCorsProxy() to the end.

so all my routes ignore your route if controller = corsproxy

have a nice day!

**Comment by jgauffin** [comment]
corrected, will not generate URLs for any mvc commands.
