### ISSUE TITLE
Applying request headers

### ISSUE THREAD

**Issue by freshcutdevelopment** [jgauffin/CorsProxy#5]
This is more of a question/ feature request than a bug really. We've got the requirement to have the custom request headers duplicated onto the proxied Ajax requests. Any way to do this easily in this library without modifying the source code to inject our headers directly?

**Comment by jgauffin** [comment]
Apologies for the late reply. I throught I had answered.

Yes, headers should get copied per default. Look here: https://github.com/jgauffin/CorsProxy/issues/5

**Comment by freshcutdevelopment** [comment]
Thanks for the clarification. closing this issue.
